# This file provides instructions for packaging.

`MooseX-XSAccessor`
	perl_version_from m`MooseX::XSAccessor`;
	version_from      m`MooseX::XSAccessor`;
	readme_from       m`MooseX::XSAccessor` ;
	requires          p`Class::XSAccessor 1.16`;
	requires          p`Moose 2.0600`;
	test_requires     p`Import::Into 1.001000`;
	test_requires     p`Test::More 0.96`;
	test_requires     p`Test::Fatal`;
	test_requires     p`Test::Moose`;
	test_requires     p`Test::Requires`;
	.

